---
title: Names EDA
author: Callan Hoskins
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)

# Parameters
names_path <- here::here("data/names.rds")

#===============================================================================

# Code
names <- read_rds(names_path)
```

```{r}
names %>% 
  filter(
    (name == "Theon" & gender == "boy") |
      (name == "Sansa" & gender == "girl") |
      (name == "Arya" & gender == "girl") |
      (name == "Khaleesi" & gender == "girl")
    ) %>% 
  ggplot(aes(year, count, color = name)) + 
  geom_line()
```
```{r}
names %>% 
  ggplot(aes(count, color = year)) + 
  facet_grid(rows = vars(gender)) + 
  geom_freqpoly()
```

```{r}
names %>% 
  group_by(gender, year) %>% 
  mutate(perc_named = count / sum(count)) %>% 
  summarize(creativity = median(perc_named)) %>% 
  ungroup() %>% 
  ggplot(aes(year, creativity, color = gender)) + 
  geom_line()
```



### Subsection

## Section 2

